<a href="https://colab.research.google.com/github/MacielBarbero/Portfolio/blob/main/Crime_limpieza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Tratamiento de datos
# ==============================================================================
import numpy as np
import pandas as pd
# Gr치ficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib.ticker as ticker
import seaborn as sns
import plotly.express as px

In [ ]:
# Leer los archivos CSV
archivo1 = pd.read_csv('/content/drive/MyDrive/Fundamentos_CaC_2024/Trabajo_final/delitos_2018.csv')
archivo2 = pd.read_csv('/content/drive/MyDrive/Fundamentos_CaC_2024/Trabajo_final/delitos_2019.csv')
archivo3 = pd.read_csv('/content/drive/MyDrive/Fundamentos_CaC_2024/Trabajo_final/delitos_2020.csv')
archivo4 = pd.read_csv('/content/drive/MyDrive/Fundamentos_CaC_2024/Trabajo_final/delitos_2021.csv')
archivo5 = pd.read_csv('/content/drive/MyDrive/Fundamentos_CaC_2024/Trabajo_final/delitos_2022.csv')
# Mostrar las primeras filas de cada archivo para ver su estructura
print("Archivo 1:")
print(archivo1.head())

print("\nArchivo 2:")
print(archivo2.head())

print("\nArchivo 3:")
print(archivo3.head())

print("\nArchivo 4:")
print(archivo4.head())

# Obtener informaci칩n sobre las columnas y tipos de datos de cada archivo
print("\nInformaci칩n sobre los archivos:")
print("Archivo 1:")
print(archivo1.info())

print("\nArchivo 2:")
print(archivo2.info())

print("\nArchivo 3:")
print(archivo3.info())

print("\nArchivo 4:")
print(archivo4.info())

print("Archivo 1:", archivo1.columns)
print("Archivo 2:", archivo2.columns)
print("Archivo 3:", archivo3.columns)
print("Archivo 4:", archivo4.columns)

Archivo 1:
   id-mapa  anio     mes        dia       fecha  franja  tipo     subtipo  \
0   500003  2018  AGOSTO    DOMINGO  2018-08-05    16.0  Robo  Robo total
1   500006  2018  AGOSTO      LUNES  2018-08-06    17.0  Robo  Robo total
2   500009  2018  AGOSTO  MIERCOLES  2018-08-08    22.0  Robo  Robo total
3   500012  2018  AGOSTO  MIERCOLES  2018-08-08    15.0  Robo  Robo total
4   500015  2018  AGOSTO    VIERNES  2018-08-10    12.0  Robo  Robo total

  uso_arma uso_moto  barrio  comuna    latitud   longitud  cantidad
0       NO       NO  RETIRO     1.0 -34.580776 -58.387188         1
1       NO       NO  RETIRO     1.0 -34.580776 -58.387188         1
2       NO       NO  RETIRO     1.0 -34.580776 -58.387188         1
3       NO       NO  RETIRO     1.0 -34.595628 -58.386597         1
4       SI       NO  RETIRO     1.0 -34.581095 -58.385790         1

Archivo 2:
   id-mapa  anio        mes        dia       fecha  franja   tipo  \
0   252569  2019      ENERO      LUNES  2019-01-28     8.0  Hurto
1   252570  2019      MARZO      LUNES  2019-03-04    11.0  Hurto
2   252571  2019      ABRIL  MIERCOLES  2019-04-10    18.0   Robo
3   252572  2019  NOVIEMBRE      LUNES  2019-11-18    12.0  Hurto
4   252573  2019      ABRIL      LUNES  2019-04-01    17.0   Robo

       subtipo uso_arma uso_moto            barrio  comuna    latitud  \
0  Hurto total       NO       NO  PARQUE PATRICIOS     4.0 -34.630835
1  Hurto total       NO       NO  PARQUE PATRICIOS     4.0 -34.628442
2   Robo total       NO       NO  PARQUE PATRICIOS     4.0 -34.630313
3  Hurto total       NO       NO  PARQUE PATRICIOS     4.0 -34.630163
4   Robo total       NO       NO  PARQUE PATRICIOS     4.0 -34.629944

    longitud  cantidad
0 -58.391528         1
1 -58.391876         1
2 -58.391512         1
3 -58.391542         1
4 -58.391882         1

Archivo 3:
   id-mapa  anio         mes        dia       fecha  franja   tipo  \
0   192085  2020       JUNIO  MIERCOLES  2020-06-10    20.0  Hurto
1   192086  2020      AGOSTO    VIERNES  2020-08-21    11.0  Hurto
2   192087  2020  SEPTIEMBRE     MARTES  2020-09-15    20.0  Hurto
3   192088  2020  SEPTIEMBRE     MARTES  2020-09-22    10.0   Robo
4   192089  2020     OCTUBRE     MARTES  2020-10-06    10.0  Hurto

       subtipo uso_arma uso_moto             barrio  comuna    latitud  \
0  Hurto total       NO       NO                NaN     NaN        NaN
1  Hurto total       NO       NO  PARQUE AVELLANEDA     9.0 -34.641905
2  Hurto total       NO       NO  PARQUE AVELLANEDA     9.0 -34.641899
3   Robo total       SI       NO  PARQUE AVELLANEDA     9.0 -34.641043
4  Hurto total       NO       NO  PARQUE AVELLANEDA     9.0 -34.641055

    longitud  cantidad
0        NaN         1
1 -58.487037         1
2 -58.480738         1
3 -58.484628         1
4 -58.484537         1

Archivo 4:
   id-mapa  anio      mes        dia       fecha  franja   tipo      subtipo  \
0   110639  2021  OCTUBRE  MIERCOLES  2021-10-06     0.0  Hurto  Hurto total
1   110640  2021  OCTUBRE     JUEVES  2021-10-07    23.0   Robo   Robo total
2   110641  2021  OCTUBRE  MIERCOLES  2021-10-06    12.0   Robo   Robo total
3   110642  2021  OCTUBRE     JUEVES  2021-10-07    20.0   Robo   Robo total
4   110643  2021  OCTUBRE     SABADO  2021-10-09    11.0  Hurto  Hurto total

  uso_arma uso_moto           barrio  comuna    latitud   longitud  cantidad
0       NO       NO  VELEZ SARSFIELD    10.0 -34.631129 -58.489377         1
1       NO       NO  VELEZ SARSFIELD    10.0 -34.624628 -58.501039         1
2       SI       NO     MONTE CASTRO    10.0 -34.623213 -58.510132         1
3       NO       NO  VELEZ SARSFIELD    10.0 -34.627172 -58.498928         1
4       NO       NO         FLORESTA    10.0 -34.626978 -58.483313         1

Informaci칩n sobre los archivos:
Archivo 1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149455 entries, 0 to 149454
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id-mapa   149455 non-null  int64
 1   anio      149455 non-null  int64
 2   mes       149455 non-null  object
 3   dia       149455 non-null  object
 4   fecha     149455 non-null  object
 5   franja    149450 non-null  float64
 6   tipo      149455 non-null  object
 7   subtipo   149455 non-null  object
 8   uso_arma  149455 non-null  object
 9   uso_moto  149455 non-null  object
 10  barrio    136252 non-null  object
 11  comuna    136252 non-null  float64
 12  latitud   136309 non-null  float64
 13  longitud  136309 non-null  float64
 14  cantidad  149455 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 17.1+ MB
None

Archivo 2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149524 entries, 0 to 149523
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id-mapa   149524 non-null  int64
 1   anio      149524 non-null  int64
 2   mes       149524 non-null  object
 3   dia       149524 non-null  object
 4   fecha     149524 non-null  object
 5   franja    149517 non-null  float64
 6   tipo      149524 non-null  object
 7   subtipo   149524 non-null  object
 8   uso_arma  149524 non-null  object
 9   uso_moto  149524 non-null  object
 10  barrio    147364 non-null  object
 11  comuna    147364 non-null  float64
 12  latitud   147367 non-null  float64
 13  longitud  147367 non-null  float64
 14  cantidad  149524 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 17.1+ MB
None

Archivo 3:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86175 entries, 0 to 86174
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id-mapa   86175 non-null  int64
 1   anio      86175 non-null  int64
 2   mes       86175 non-null  object
 3   dia       86175 non-null  object
 4   fecha     86175 non-null  object
 5   franja    85656 non-null  float64
 6   tipo      86175 non-null  object
 7   subtipo   86175 non-null  object
 8   uso_arma  86175 non-null  object
 9   uso_moto  86175 non-null  object
 10  barrio    84876 non-null  object
 11  comuna    84876 non-null  float64
 12  latitud   84877 non-null  float64
 13  longitud  84877 non-null  float64
 14  cantidad  86175 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 9.9+ MB
None

Archivo 4:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111962 entries, 0 to 111961
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id-mapa   111962 non-null  int64
 1   anio      111962 non-null  int64
 2   mes       111962 non-null  object
 3   dia       111962 non-null  object
 4   fecha     111962 non-null  object
 5   franja    110222 non-null  float64
 6   tipo      111962 non-null  object
 7   subtipo   111962 non-null  object
 8   uso_arma  111962 non-null  object
 9   uso_moto  111962 non-null  object
 10  barrio    109378 non-null  object
 11  comuna    109378 non-null  float64
 12  latitud   109383 non-null  float64
 13  longitud  109383 non-null  float64
 14  cantidad  111962 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 12.8+ MB
None
Archivo 1: Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_arma', 'uso_moto', 'barrio', 'comuna', 'latitud', 'longitud',
       'cantidad'],
      dtype='object')
Archivo 2: Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_arma', 'uso_moto', 'barrio', 'comuna', 'latitud', 'longitud',
       'cantidad'],
      dtype='object')
Archivo 3: Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_arma', 'uso_moto', 'barrio', 'comuna', 'latitud', 'longitud',
       'cantidad'],
      dtype='object')
Archivo 4: Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_arma', 'uso_moto', 'barrio', 'comuna', 'latitud', 'longitud',
       'cantidad'],
      dtype='object')

In [ ]:
# Uno las csv en uno solo.
datos_unidos = pd.concat([archivo1, archivo2, archivo3, archivo4], ignore_index=True)

# Mostrar los primeros registros del conjunto de datos unido
print(datos_unidos.head())
print("\n")

# Hago una copia del conjunto de datos unido.
df = datos_unidos.copy()
df.info()
print("\n")
print("La dimensi칩n del data frame es: ",df.shape)
print("\n")

df

   id-mapa  anio     mes        dia       fecha  franja  tipo     subtipo  \
0   500003  2018  AGOSTO    DOMINGO  2018-08-05    16.0  Robo  Robo total
1   500006  2018  AGOSTO      LUNES  2018-08-06    17.0  Robo  Robo total
2   500009  2018  AGOSTO  MIERCOLES  2018-08-08    22.0  Robo  Robo total
3   500012  2018  AGOSTO  MIERCOLES  2018-08-08    15.0  Robo  Robo total
4   500015  2018  AGOSTO    VIERNES  2018-08-10    12.0  Robo  Robo total

  uso_arma uso_moto  barrio  comuna    latitud   longitud  cantidad
0       NO       NO  RETIRO     1.0 -34.580776 -58.387188         1
1       NO       NO  RETIRO     1.0 -34.580776 -58.387188         1
2       NO       NO  RETIRO     1.0 -34.580776 -58.387188         1
3       NO       NO  RETIRO     1.0 -34.595628 -58.386597         1
4       SI       NO  RETIRO     1.0 -34.581095 -58.385790         1


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497116 entries, 0 to 497115
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id-mapa   497116 non-null  int64
 1   anio      497116 non-null  int64
 2   mes       497116 non-null  object
 3   dia       497116 non-null  object
 4   fecha     497116 non-null  object
 5   franja    494845 non-null  float64
 6   tipo      497116 non-null  object
 7   subtipo   497116 non-null  object
 8   uso_arma  497116 non-null  object
 9   uso_moto  497116 non-null  object
 10  barrio    477870 non-null  object
 11  comuna    477870 non-null  float64
 12  latitud   477936 non-null  float64
 13  longitud  477936 non-null  float64
 14  cantidad  497116 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 56.9+ MB


La dimensi칩n del data frame es:  (497116, 15)

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
0,500003,2018,AGOSTO,DOMINGO,2018-08-05,16.0,Robo,Robo total,NO,NO,RETIRO,1.0,-34.580776,-58.387188,1
1,500006,2018,AGOSTO,LUNES,2018-08-06,17.0,Robo,Robo total,NO,NO,RETIRO,1.0,-34.580776,-58.387188,1
2,500009,2018,AGOSTO,MIERCOLES,2018-08-08,22.0,Robo,Robo total,NO,NO,RETIRO,1.0,-34.580776,-58.387188,1
3,500012,2018,AGOSTO,MIERCOLES,2018-08-08,15.0,Robo,Robo total,NO,NO,RETIRO,1.0,-34.595628,-58.386597,1
4,500015,2018,AGOSTO,VIERNES,2018-08-10,12.0,Robo,Robo total,SI,NO,RETIRO,1.0,-34.581095,-58.385790,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497111,1114383,2021,DICIEMBRE,DOMINGO,2021-12-12,6.0,Vialidad,Muertes por siniestros viales,NO,NO,BALVANERA,3.0,-34.610119,-58.405971,1
497112,1114384,2021,DICIEMBRE,LUNES,2021-12-13,17.0,Vialidad,Muertes por siniestros viales,NO,NO,PARQUE CHACABUCO,7.0,-34.645363,-58.433471,1
497113,1114385,2021,DICIEMBRE,MIERCOLES,2021-12-15,10.0,Vialidad,Muertes por siniestros viales,NO,NO,PARQUE AVELLANEDA,9.0,-34.649554,-58.470791,1
497114,1114386,2021,DICIEMBRE,LUNES,2021-12-20,1.0,Vialidad,Muertes por siniestros viales,NO,NO,PARQUE AVELLANEDA,9.0,-34.652298,-58.467767,1
497115,1114387,2021,DICIEMBRE,JUEVES,2021-12-30,0.0,Vialidad,Muertes por siniestros viales,NO,NO,VILLA SANTA RITA,11.0,-34.619676,-58.472919,1

In [ ]:
print("Estad칤stica descriptiva:")
df.describe()

Estad칤stica descriptiva:

,id-mapa,anio,franja,comuna,latitud,longitud,cantidad
count,4.971160e+05,497116.000000,494845.000000,477870.000000,477936.000000,477936.000000,497116.0
mean,5.192762e+05,2019.323152,13.388461,7.289928,-34.613496,-58.435439,1.0
std,3.120078e+05,1.127148,6.390438,4.575485,0.031099,0.046784,0.0
min,1.106390e+05,2018.000000,0.000000,1.000000,-34.929085,-70.607629,1.0
25%,2.349178e+05,2018.000000,9.000000,3.000000,-34.633944,-58.468935,1.0
50%,3.591965e+05,2019.000000,14.000000,7.000000,-34.612467,-58.433025,1.0
75%,8.514712e+05,2020.000000,19.000000,11.000000,-34.593133,-58.400256,1.0
max,1.114511e+06,2021.000000,23.000000,15.000000,-31.420083,-58.241887,1.0

In [ ]:
# Cambio el formato de la columna fecha.
df['fecha'] = pd.to_datetime(df['fecha'], format ='%Y-%m-%d')
print("Nuevo formato de la fecha: ",df['fecha'].dtype)

# Elimino filas con todos los valores faltantes.
print("La cantidad de filas absolutamente vac칤as es: ", df.isna().all(axis=1).sum())
df = df.dropna(how='all')

print("La dimensi칩n del data frame es: ",df.shape)

Nuevo formato de la fecha:  datetime64[ns]
La cantidad de filas absolutamente vac칤as es:  0
La dimensi칩n del data frame es:  (497116, 15)

In [ ]:
# Duplicados contarlos:
print("La cantidad de filas duplicadas: ",df.duplicated().sum())

# Duplicados mostrarlos:
# df[df.duplicated(keep='first')] # keep='first'/'last'/False(marca todas como duplicados)

# Duplicados borrarlos:
# df.drop_duplicates()

df.rename(columns={'franja': 'franja_horaria'}, inplace=True)

# Exploratorios
print("Resumen de valores faltantes por columna:", df.isnull().sum())
print("Exploratorios: ")
df_temp = df.isna().sum().sort_values()
df_temp[df_temp>0]

La cantidad de filas duplicadas:  0
Resumen de valores faltantes por columna: id-mapa               0
anio                  0
mes                   0
dia                   0
fecha                 0
franja_horaria     2271
tipo                  0
subtipo               0
uso_arma              0
uso_moto              0
barrio            19246
comuna            19246
latitud           19180
longitud          19180
cantidad              0
dtype: int64
Exploratorios:

franja_horaria     2271
latitud           19180
longitud          19180
barrio            19246
comuna            19246
dtype: int64

In [ ]:
# Imputar 'franja_horaria' con la moda
df['franja_horaria'].fillna(df['franja_horaria'].mode()[0], inplace=True)

In [ ]:
from sklearn.impute import KNNImputer

# Funci칩n para imputar latitud y longitud usando KNN con KNeighborsRegressor
def impute_lat_lon(df):
    # Concatenar latitud y longitud en una sola columna
    df['coordenada'] = df['latitud'].astype(str) + ',' + df['longitud'].astype(str)

    # Crear instancia del imputador KNN
    imputer = KNNImputer(n_neighbors=5)

    # Imputar latitud y longitud
    df[['latitud', 'longitud']] = imputer.fit_transform(df[['latitud', 'longitud']])

    # Eliminar la columna 'coordenada' ya que no es necesaria despu칠s de la imputaci칩n
    df.drop(columns=['coordenada'], inplace=True)

    return df

# Aplicar la funci칩n para imputar latitud y longitud
df = impute_lat_lon(df)

In [ ]:
# Reviso si se llenaron valores faltantes en latitud y longitud.

print("Resumen de valores faltantes luego de llenado faltantes:", df.isnull().sum())

Resumen de valores faltantes luego de llenado faltantes: id-mapa               0
anio                  0
mes                   0
dia                   0
fecha                 0
franja_horaria        0
tipo                  0
subtipo               0
uso_arma              0
uso_moto              0
barrio            19246
comuna            19246
latitud               0
longitud              0
cantidad              0
dtype: int64

# Genero intervalos de latitud-longitud para asignar barrios.

In [ ]:
from collections import defaultdict

# Definir una funci칩n para generar rangos de latitud y longitud
def generate_ranges(lat, lon, precision):
    lat_range = round(float(lat) / precision) * precision
    lon_range = round(float(lon) / precision) * precision
    return (lat_range, lon_range)

# Definir la precisi칩n deseada para los rangos
precision = 0.01  # Ajusta este valor seg칰n la precisi칩n requerida

# Creamos un diccionario donde cada barrio est치 asociado a un rango de coordenadas (latitud, longitud)
barrio_to_ranges = defaultdict(list)
for index, row in df.dropna(subset=['latitud', 'longitud', 'barrio']).iterrows():
    lat_range, lon_range = generate_ranges(row['latitud'], row['longitud'], precision)
    barrio_to_ranges[row['barrio']].append((lat_range, lon_range))

# Asignar barrio basado en los rangos de coordenadas asociados a cada barrio
for i, row in df.iterrows():
    if pd.isnull(row['barrio']):
        lat_range, lon_range = generate_ranges(row['latitud'], row['longitud'], precision)
        for barrio, ranges in barrio_to_ranges.items():
            if (lat_range, lon_range) in ranges:
                df.at[i, 'barrio'] = barrio
                break

print(df)

        id-mapa  anio        mes        dia      fecha  franja_horaria  \
0        500003  2018     AGOSTO    DOMINGO 2018-08-05            16.0
1        500006  2018     AGOSTO      LUNES 2018-08-06            17.0
2        500009  2018     AGOSTO  MIERCOLES 2018-08-08            22.0
3        500012  2018     AGOSTO  MIERCOLES 2018-08-08            15.0
4        500015  2018     AGOSTO    VIERNES 2018-08-10            12.0
...         ...   ...        ...        ...        ...             ...
497111  1114383  2021  DICIEMBRE    DOMINGO 2021-12-12             6.0
497112  1114384  2021  DICIEMBRE      LUNES 2021-12-13            17.0
497113  1114385  2021  DICIEMBRE  MIERCOLES 2021-12-15            10.0
497114  1114386  2021  DICIEMBRE      LUNES 2021-12-20             1.0
497115  1114387  2021  DICIEMBRE     JUEVES 2021-12-30             0.0

            tipo                        subtipo uso_arma uso_moto  \
0           Robo                     Robo total       NO       NO
1           Robo                     Robo total       NO       NO
2           Robo                     Robo total       NO       NO
3           Robo                     Robo total       NO       NO
4           Robo                     Robo total       SI       NO
...          ...                            ...      ...      ...
497111  Vialidad  Muertes por siniestros viales       NO       NO
497112  Vialidad  Muertes por siniestros viales       NO       NO
497113  Vialidad  Muertes por siniestros viales       NO       NO
497114  Vialidad  Muertes por siniestros viales       NO       NO
497115  Vialidad  Muertes por siniestros viales       NO       NO

                   barrio  comuna    latitud   longitud  cantidad
0                  RETIRO     1.0 -34.580776 -58.387188         1
1                  RETIRO     1.0 -34.580776 -58.387188         1
2                  RETIRO     1.0 -34.580776 -58.387188         1
3                  RETIRO     1.0 -34.595628 -58.386597         1
4                  RETIRO     1.0 -34.581095 -58.385790         1
...                   ...     ...        ...        ...       ...
497111          BALVANERA     3.0 -34.610119 -58.405971         1
497112   PARQUE CHACABUCO     7.0 -34.645363 -58.433471         1
497113  PARQUE AVELLANEDA     9.0 -34.649554 -58.470791         1
497114  PARQUE AVELLANEDA     9.0 -34.652298 -58.467767         1
497115   VILLA SANTA RITA    11.0 -34.619676 -58.472919         1

[497116 rows x 15 columns]

In [ ]:
# Reviso si se llenaron valores faltantes en barrios.

print("Resumen de valores faltantes luego de llenado faltantes:", df.isnull().sum())

Resumen de valores faltantes luego de llenado faltantes: id-mapa               0
anio                  0
mes                   0
dia                   0
fecha                 0
franja_horaria        0
tipo                  0
subtipo               0
uso_arma              0
uso_moto              0
barrio               58
comuna            19246
latitud               0
longitud              0
cantidad              0
dtype: int64

# ASIGNACI칍N DE COMUNAS.

Teniendo en cuenta la siguiente informaci칩n asigno barrios a las respectivas comunas.
---

* Comuna 1: Retiro, San Nicol치s, Puerto Madero, San Telmo, Monserrat y Constituci칩n.
* Comuna 2: Recoleta.
* Comuna 3: Balvanera y San Crist칩bal.
* Comuna 4: La Boca, Barracas, Parque Patricios y Nueva Pompeya.
* Comuna 5: Almagro y Boedo.
* Comuna 6: Caballito.
* Comuna 7: Flores y Parque Chacabuco.
* Comuna 8: Villa Soldati, Villa Riachuelo y Villa Lugano.
* Comuna 9: Liniers, Mataderos y Parque Avellaneda.
* Comuna 10: Floresta, Monte Castro, V칠lez S치rsfield y Villa Luro.
* Comuna 11: Villa General Mitre, Villa Devoto, Villa del Parque y Villa Santa Rita.
* Comuna 12: Coghlan, Saavedra, Villa Urquiza y Villa Pueyrred칩n.
* Comuna 13: Belgrano, Colegiales y N칰침ez.
* Comuna 14: Palermo.
* Comuna 15: Chacarita, Villa Crespo y La Paternal.

In [ ]:
# Necesito conocer la forma exacta de los string para que mapee.
print(df['barrio'].unique())

['RETIRO' 'SAN NICOLAS' 'BALVANERA' 'MONSERRAT' 'SAN CRISTOBAL'
 'CONSTITUCION' 'SAN TELMO' 'RECOLETA' 'NUEVA POMPEYA' 'PARQUE PATRICIOS'
 'BARRACAS' 'BOCA' 'ALMAGRO' 'BOEDO' 'CABALLITO' 'FLORES' 'VILLA SOLDATI'
 'PARQUE CHACABUCO' 'VILLA LUGANO' 'VILLA RIACHUELO' 'LINIERS'
 'VILLA SANTA RITA' 'VILLA DEVOTO' 'VILLA DEL PARQUE' 'SAAVEDRA'
 'VILLA PUEYRREDON' 'VILLA URQUIZA' 'COGHLAN' 'BELGRANO' 'PATERNAL'
 'CHACARITA' 'VILLA CRESPO' 'VILLA ORTUZAR' 'PALERMO' nan 'MONTE CASTRO'
 'VELEZ SARSFIELD' 'FLORESTA' 'VILLA REAL' 'VERSALLES' 'VILLA LURO'
 'PARQUE AVELLANEDA' 'VILLA GRAL. MITRE' 'NU칌EZ' 'AGRONOMIA' 'COLEGIALES'
 'PARQUE CHAS' 'PUERTO MADERO' 'MATADEROS']

In [ ]:
# Define el mapeo de barrios a comunas
barrio_to_comuna = {
    'RETIRO': 1, 'SAN NICOLAS': 1, 'BALVANERA': 3, 'MONSERRAT': 1, 'SAN CRISTOBAL': 3,
    'CONSTITUCION': 1, 'SAN TELMO': 1, 'RECOLETA': 2, 'NUEVA POMPEYA': 4, 'PARQUE PATRICIOS': 4,
    'BARRACAS': 4, 'BOCA': 4, 'ALMAGRO': 5, 'BOEDO': 5, 'CABALLITO': 6, 'FLORES': 7,
    'VILLA SOLDATI': 8, 'PARQUE CHACABUCO': 7, 'VILLA LUGANO': 8, 'VILLA RIACHUELO': 8,
    'LINIERS': 9, 'VILLA SANTA RITA': 11, 'VILLA DEVOTO': 11, 'VILLA DEL PARQUE': 11,
    'SAAVEDRA': 12, 'VILLA PUEYRREDON': 12, 'VILLA URQUIZA': 12, 'COGHLAN': 12,
    'BELGRANO': 13, 'PATERNAL': 15, 'CHACARITA': 15, 'VILLA CRESPO': 15, 'VILLA ORTUZAR': 15,
    'PALERMO': 14, 'MONTE CASTRO': 10, 'VELEZ SARSFIELD': 10, 'FLORESTA': 10, 'VILLA REAL': 10,
    'VERSALLES': 10, 'VILLA LURO': 10, 'PARQUE AVELLANEDA': 9, 'VILLA GRAL. MITRE': 11,
    'NU칌EZ': 13, 'AGRONOMIA': 15, 'COLEGIALES': 13, 'PARQUE CHAS': 15, 'PUERTO MADERO': 1,
    'MATADEROS': 9
}

# Rellenar valores faltantes en 'comuna' basados en el mapeo de barrios a comunas
df['comuna'] = df['barrio'].map(barrio_to_comuna).fillna(df['comuna'])

In [ ]:
# Reviso si se llenaron valores faltantes en comunas.

print("Resumen de valores faltantes luego de llenado faltantes:", df.isnull().sum())

# Llenado de faltantes:
# df['column'] = df['column'].fillna(df['column'].mean(), inplace = True)
# df['column'] = df['column'].fillna()

Resumen de valores faltantes luego de llenado faltantes: id-mapa            0
anio               0
mes                0
dia                0
fecha              0
franja_horaria     0
tipo               0
subtipo            0
uso_arma           0
uso_moto           0
barrio            58
comuna            58
latitud            0
longitud           0
cantidad           0
dtype: int64

In [ ]:
# Eliminar columnas innecesarias o redundantes:
df.drop(columns = ['id-mapa', 'cantidad'], axis = 1, inplace = True)
# No lo asigno a df porque el inplace = True lo modifica directamente en el df
print(df)

        anio        mes        dia      fecha  franja_horaria      tipo  \
0       2018     AGOSTO    DOMINGO 2018-08-05            16.0      Robo
1       2018     AGOSTO      LUNES 2018-08-06            17.0      Robo
2       2018     AGOSTO  MIERCOLES 2018-08-08            22.0      Robo
3       2018     AGOSTO  MIERCOLES 2018-08-08            15.0      Robo
4       2018     AGOSTO    VIERNES 2018-08-10            12.0      Robo
...      ...        ...        ...        ...             ...       ...
497111  2021  DICIEMBRE    DOMINGO 2021-12-12             6.0  Vialidad
497112  2021  DICIEMBRE      LUNES 2021-12-13            17.0  Vialidad
497113  2021  DICIEMBRE  MIERCOLES 2021-12-15            10.0  Vialidad
497114  2021  DICIEMBRE      LUNES 2021-12-20             1.0  Vialidad
497115  2021  DICIEMBRE     JUEVES 2021-12-30             0.0  Vialidad

                              subtipo uso_arma uso_moto             barrio  \
0                          Robo total       NO       NO             RETIRO
1                          Robo total       NO       NO             RETIRO
2                          Robo total       NO       NO             RETIRO
3                          Robo total       NO       NO             RETIRO
4                          Robo total       SI       NO             RETIRO
...                               ...      ...      ...                ...
497111  Muertes por siniestros viales       NO       NO          BALVANERA
497112  Muertes por siniestros viales       NO       NO   PARQUE CHACABUCO
497113  Muertes por siniestros viales       NO       NO  PARQUE AVELLANEDA
497114  Muertes por siniestros viales       NO       NO  PARQUE AVELLANEDA
497115  Muertes por siniestros viales       NO       NO   VILLA SANTA RITA

        comuna    latitud   longitud
0          1.0 -34.580776 -58.387188
1          1.0 -34.580776 -58.387188
2          1.0 -34.580776 -58.387188
3          1.0 -34.595628 -58.386597
4          1.0 -34.581095 -58.385790
...        ...        ...        ...
497111     3.0 -34.610119 -58.405971
497112     7.0 -34.645363 -58.433471
497113     9.0 -34.649554 -58.470791
497114     9.0 -34.652298 -58.467767
497115    11.0 -34.619676 -58.472919

[497116 rows x 13 columns]

In [ ]:
# Guardar el conjunto de datos unido en un nuevo archivo CSV
# df.to_csv('base_limpia.csv', index=False) # Aplicar refresh en el men칰 para que aprezca.

In [ ]:
# df[df['barrio'].isnull() & df['comuna'].isnull()]

,anio,mes,dia,fecha,franja_horaria,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud
371,2018,AGOSTO,MARTES,2018-08-21,1.0,Robo,Robo total,SI,NO,NaN,NaN,-34.694658,-58.437084
372,2018,AGOSTO,MARTES,2018-08-21,13.0,Robo,Robo total,NO,NO,NaN,NaN,-34.694658,-58.437084
373,2018,AGOSTO,LUNES,2018-08-27,19.0,Robo,Robo total,NO,NO,NaN,NaN,-34.761182,-58.430248
374,2018,AGOSTO,LUNES,2018-08-27,19.0,Robo,Robo total,NO,NO,NaN,NaN,-34.761182,-58.430248
6303,2018,MAYO,MARTES,2018-05-22,22.0,Robo,Robo total,NO,NO,NaN,NaN,-34.479665,-58.703033
6304,2018,OCTUBRE,LUNES,2018-10-22,19.0,Robo,Robo automotor,SI,NO,NaN,NaN,-34.657024,-58.675398
6305,2018,OCTUBRE,JUEVES,2018-10-04,12.0,Robo,Robo total,NO,NO,NaN,NaN,-34.849583,-58.657086
6306,2018,OCTUBRE,JUEVES,2018-10-04,20.0,Robo,Robo automotor,SI,NO,NaN,NaN,-34.786248,-58.622966
6307,2018,OCTUBRE,JUEVES,2018-10-11,17.0,Robo,Robo total,NO,NO,NaN,NaN,-34.655861,-58.616721
6308,2018,JULIO,DOMINGO,2018-07-01,22.0,Robo,Robo total,NO,NO,NaN,NaN,-34.612849,-58.589466
6309,2018,ABRIL,LUNES,2018-04-30,8.0,Robo,Robo total,NO,NO,NaN,NaN,-34.661049,-58.581858
6310,2018,JULIO,MARTES,2018-07-31,19.0,Robo,Robo total,NO,NO,NaN,NaN,-34.644155,-58.558193
6311,2018,JULIO,SABADO,2018-07-07,18.0,Robo,Robo total,NO,NO,NaN,NaN,-34.639977,-58.549670
6312,2018,JULIO,MARTES,2018-07-10,21.0,Robo,Robo total,NO,NO,NaN,NaN,-34.663480,-58.543072
6313,2018,MAYO,JUEVES,2018-05-17,20.0,Robo,Robo total,NO,NO,NaN,NaN,-34.573344,-58.541836
6314,2018,OCTUBRE,LUNES,2018-10-15,15.0,Robo,Robo total,NO,NO,NaN,NaN,-34.577708,-58.539473
6315,2018,MARZO,DOMINGO,2018-03-25,15.0,Robo,Robo total,SI,NO,NaN,NaN,-34.577511,-58.538766
6320,2018,OCTUBRE,VIERNES,2018-10-12,20.0,Robo,Robo total,NO,NO,NaN,NaN,-34.560384,-58.528730
6321,2018,JULIO,MARTES,2018-07-10,17.0,Robo,Robo total,NO,NO,NaN,NaN,-34.561710,-58.527306
6322,2018,OCTUBRE,SABADO,2018-10-06,6.0,Robo,Robo total,NO,NO,NaN,NaN,-34.576431,-58.525051
6323,2018,OCTUBRE,DOMINGO,2018-10-14,23.0,Robo,Robo total,NO,NO,NaN,NaN,-34.576431,-58.525051
6327,2018,NOVIEMBRE,LUNES,2018-11-05,20.0,Robo,Robo total,SI,SI,NaN,NaN,-34.690257,-58.498199
6329,2018,MAYO,SABADO,2018-05-19,1.0,Robo,Robo automotor,SI,NO,NaN,NaN,-34.695838,-58.486922
6332,2018,SEPTIEMBRE,JUEVES,2018-09-06,14.0,Robo,Robo total,SI,NO,NaN,NaN,-34.523064,-58.477626
6336,2018,NOVIEMBRE,DOMINGO,2018-11-04,17.0,Robo,Robo total,NO,NO,NaN,NaN,-34.819443,-58.463105
6338,2018,OCTUBRE,JUEVES,2018-10-04,19.0,Robo,Robo total,NO,NO,NaN,NaN,-34.709906,-58.447929
6339,2018,OCTUBRE,DOMINGO,2018-10-07,9.0,Robo,Robo total,NO,NO,NaN,NaN,-34.701684,-58.437552
6340,2018,OCTUBRE,VIERNES,2018-10-05,15.0,Robo,Robo total,NO,NO,NaN,NaN,-34.696320,-58.422438
6341,2018,OCTUBRE,SABADO,2018-10-20,10.0,Robo,Robo total,NO,NO,NaN,NaN,-34.696320,-58.422438
6344,2018,JULIO,JUEVES,2018-07-26,22.0,Robo,Robo total,NO,NO,NaN,NaN,-34.699225,-58.390069
63163,2018,OCTUBRE,DOMINGO,2018-10-14,21.0,Robo,Robo total,NO,NO,NaN,NaN,-34.728241,-58.241887
71136,2018,OCTUBRE,DOMINGO,2018-10-21,11.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.157817,-58.958469
71137,2018,AGOSTO,LUNES,2018-08-20,18.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.582384,-58.751723
71138,2018,JULIO,LUNES,2018-07-09,18.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.592512,-58.619134
71139,2018,OCTUBRE,MARTES,2018-10-23,1.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.749748,-58.584591
71140,2018,OCTUBRE,MARTES,2018-10-09,18.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.681427,-58.545931
71141,2018,OCTUBRE,MARTES,2018-10-23,10.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.572561,-58.545838
71142,2018,JULIO,JUEVES,2018-07-12,10.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.575951,-58.537270
71148,2018,OCTUBRE,MIERCOLES,2018-10-24,14.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.584437,-58.529575
71153,2018,OCTUBRE,VIERNES,2018-10-12,19.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.584524,-58.529267
71224,2018,OCTUBRE,MARTES,2018-10-02,21.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.586040,-58.527569
71225,2018,OCTUBRE,MARTES,2018-10-02,17.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.586040,-58.527569
71226,2018,OCTUBRE,MARTES,2018-10-09,22.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.586040,-58.527569
71581,2018,OCTUBRE,DOMINGO,2018-10-14,13.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.563654,-58.523506
72770,2018,ENERO,SABADO,2018-01-20,14.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.712827,-58.511015
77300,2018,ABRIL,JUEVES,2018-04-05,21.0,Hurto,Hurto total,NO,NO,NaN,NaN,-34.526817,-58.484245
79051,2018,JUNIO,JUEVES,2018-06-21,9.0,Hurto,Hurto automotor,NO,NO,NaN,NaN,-34.522473,-58.476197
86051,2018,AGOSTO,JUEVES,2018-08-30,20.0,Hurto,Hurto automotor,NO,NO,NaN,NaN,-34.713895,-58.447715
87647,2018,AGOSTO,DOMINGO,2018-08-26,10.0,Hurto,Hurto automotor,NO,NO,NaN,NaN,-34.696864,-58.440815
100720,2018,ENERO,MIERCOLES,2018-01-17,22.0,Hurto,Hurto automotor,NO,NO,NaN,NaN,-34.707120,-58.391891
273342,2019,NOVIEMBRE,DOMINGO,2019-11-03,19.0,Lesiones,Lesiones Dolosas,NO,NO,NaN,NaN,-34.929085,-58.374068
273343,2019,JULIO,DOMINGO,2019-07-21,6.0,Lesiones,Lesiones Dolosas,NO,NO,NaN,NaN,-34.711911,-58.492146
298751,2019,JULIO,LUNES,2019-07-22,21.0,Lesiones,Lesiones Dolosas,NO,NO,NaN,NaN,-34.526608,-58.504469
366581,2020,MARZO,MARTES,2020-03-03,1.0,Lesiones,Lesiones Dolosas,NO,NO,NaN,NaN,-34.668984,-58.393781
475932,2021,MARZO,MARTES,2021-03-02,0.0,Amenazas,Amenazas,NO,NO,NaN,NaN,-34.707500,-58.383100
477764,2021,DICIEMBRE,VIERNES,2021-12-10,8.0,Amenazas,Amenazas,NO,NO,NaN,NaN,-34.666562,-58.365822
496900,2021,JULIO,VIERNES,2021-07-09,0.0,Amenazas,Amenazas,NO,NO,NaN,NaN,-33.419360,-70.607629
496901,2021,JULIO,LUNES,2021-07-26,0.0,Amenazas,Amenazas,NO,NO,NaN,NaN,-31.420083,-64.188776

In [ ]:
# # Contar y listar valores 칰nicos en la columna 'Comuna'
# comuna_value_counts = df['comuna'].value_counts()
# print("Valores 칰nicos en la columna 'Comuna' con sus frecuencias:")
# print(comuna_value_counts)

# # Contar y listar valores 칰nicos en la columna 'Barrio'
# barrio_value_counts = df['barrio'].value_counts()
# print("\nValores 칰nicos en la columna 'Barrio' con sus frecuencias:")
# print(barrio_value_counts)

Valores 칰nicos en la columna 'Comuna' con sus frecuencias:
comuna
1.0     65278
4.0     45418
3.0     42038
6.0     40096
14.0    36721
7.0     35349
8.0     30296
15.0    28460
13.0    28305
9.0     27617
5.0     26854
12.0    24072
10.0    22463
11.0    22433
2.0     21658
Name: count, dtype: int64

Valores 칰nicos en la columna 'Barrio' con sus frecuencias:
barrio
CABALLITO            40096
PALERMO              36721
BALVANERA            33173
FLORES               25608
RECOLETA             21658
ALMAGRO              19165
VILLA LUGANO         18824
SAN NICOLAS          18437
BARRACAS             16723
BELGRANO             15248
CONSTITUCION         15162
RETIRO               13526
VILLA CRESPO         12671
MATADEROS            11551
NUEVA POMPEYA        11516
MONSERRAT            11358
VILLA URQUIZA        10028
PARQUE CHACABUCO      9741
VILLA SOLDATI         9066
SAN CRISTOBAL         8865
PARQUE PATRICIOS      8600
BOCA                  8579
PARQUE AVELLANEDA     8388
VILLA DEVOTO          7868
SAAVEDRA              7760
BOEDO                 7689
LINIERS               7678
NU칌EZ                 7256
FLORESTA              6449
CHACARITA             6430
COLEGIALES            5801
SAN TELMO             5771
VILLA DEL PARQUE      5601
VILLA GRAL. MITRE     4606
VELEZ SARSFIELD       4423
VILLA SANTA RITA      4358
VILLA PUEYRREDON      4219
VILLA LURO            4028
MONTE CASTRO          3987
PATERNAL              3075
VILLA ORTUZAR         2737
VILLA RIACHUELO       2406
COGHLAN               2065
PARQUE CHAS           1875
VERSALLES             1845
VILLA REAL            1731
AGRONOMIA             1672
PUERTO MADERO         1024
Name: count, dtype: int64

In [ ]:
# Guardar el DataFrame principal (df) en un archivo CSV en Google Drive
output_path = '/content/drive/MyDrive/Fundamentos_CaC_2024/Trabajo_final/base_limpia.csv'
df.to_csv(output_path, index=False)